services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
        #image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    container_name: elasticsearch-in-action-8.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: kibana-in-action-8.17.4
    environment:
      - elasticsearch.url=http://elasticsearch:9200
      #- ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - 5601:5601
  # slack과 연결하기 위한 Elasticsearch connector 설정
  connector_service:
    image: docker.elastic.co/integrations/elastic-connectors:8.17.4
    container_name: elasticsearch-connector-service
    volumes:
      - /home/peeljun/elastic-connectors:/config
    command: ["/app/bin/elastic-ingest", "-c", "/config/config.yml"]